#!/bin/sh

[ -x /usr/bin/pygmentize -o -x /usr/local/bin/pygmentize ] || exit 0
[ -f $1 ] || exit 1

case "$1" in
    *.awk|*.groff|*.java|*.js|*.m4|*.php|*.pl|*.pm|*.pod|*.sh|\
    *.ad[asb]|*.asm|*.inc|*.[ch]|*.[ch]pp|*.[ch]xx|*.cc|*.hh|\
    *.lsp|*.l|*.pas|*.p|*.xml|*.xps|*.xsl|*.axp|*.ppd|*.pov|\
    *.diff|*.patch|*.py|*.rb|*.sql|*.ebuild|*.eclass)
        pygmentize -f 256 -O style=emacs "$1";;
    .bashrc|.bash_aliases|.bash_environment|.profile)
        pygmentize -f 256 -O style=emacs -l sh "$1"
        ;;
    *)
        head -n 1 $1 | grep "#\!/bin/\(ba\)\?sh" > /dev/null
        if [ "$?" -eq "0" ]; then
            pygmentize -f 256 -O style=emacs -l sh "$1"
        else
            #pygmentize -f 256 -O style=emacs -l `pygmentize -N "$1"` $1
            exit 1
        fi
esac

exit 0

