set-option -g allow-passthrough on
set -g set-clipboard on

# See if this fixes slow ESC issues.
# http://unix.stackexchange.com/questions/23138/esc-key-causes-a-small-delay-in-terminal-due-to-its-alt-behavior
set -s escape-time 10

# Default terminal (tmux-256color supports true color for vim termguicolors)
set -g default-terminal "tmux-256color"

set-option -g automatic-rename on
set -g renumber-windows on
set -g focus-events on

# Scrollback buffer size
set -g history-limit 50000

# Start window and pane indices at 1.
set -g base-index 1
set -g pane-base-index 1

# Mouse works as expected
set -g mouse on
# Toggle mouse on with ^B m
bind m set -g mouse on \; display 'Mouse: ON'
# Toggle mouse off with ^B M
bind M set -g mouse off \; display 'Mouse: OFF'

setw -g monitor-activity on
set -g visual-activity off

# Status bar styling and content.
set -g status-style bg=black,fg=white
set -g status-left '#S'

set -ga terminal-overrides ',xterm*:XT:smcup@:rmcup@'
set -ga terminal-overrides ',xterm*:Tc'
set -g set-titles on
set -g set-titles-string "#T"

# Highlight the active window in the status bar.
set-window-option -g window-status-current-style bg=yellow,fg=black

# Cycle panes.
bind b select-pane -t :.+

# C-n also does next window
bind C-n next-window

# New windows start in the active pane's directory.
bind c new-window -c "#{pane_current_path}"

# Reload tmux config.
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# Reorder windows.
bind -r < swap-window -t -1 \; select-window -t -1
bind -r > swap-window -t +1 \; select-window -t +1

# Use vim keybindings in copy mode
setw -g mode-keys vi

# Split windows with | and -, starting in the active pane's directory.
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind _ split-window -v -p 25 -c "#{pane_current_path}"
bind \\ split-window -h -p 35 -c "#{pane_current_path}"

# Setup 'v' to begin selection as in Vim
bind Escape copy-mode
bind / copy-mode \; send-key /
unbind p
bind p paste-buffer

# moving between panes with vim movement keys
unbind h
unbind j
unbind k
unbind l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# resize panes with vim movement keys
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# moving between windows with vim movement keys
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+
